vich_uploader:
  db_driver: orm

  mappings:
    pin_image:
      uri_prefix: /uploads/pin
      upload_destination: '%kernel.project_dir%/public/uploads/pin'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    user_image:
      uri_prefix: /uploads/user
      upload_destination: '%kernel.project_dir%/public/uploads/user'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
